/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cadastro_2.java
 *
 * Created on 15/09/2012, 14:24:10
 */
package Interface;

/**
 *
 * @author aluno
 */
import Controle.ControleBasico;
import Controle.ControleProjeto;
import Negocio.Projeto;
import Util.Diversos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class JFrmProjeto extends javax.swing.JFrame {

    ControleBasico cP;
    final String titulo;
  
    public JFrmProjeto() {
        this.cP = new ControleProjeto();
        this.titulo =  "Manipulação dos dados do projeto";
        initComponents();
         setSize(450, 250);
        setResizable(false);
        setLocationRelativeTo(null);
        try {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
             IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrmProjeto.class.getName()).log(Level.SEVERE, null, ex);
          }   
    }
     
    private void carregaObjetos(Projeto p){
       jTxtCodigo.setText(String.valueOf(p.getCodigo()));
       jTxtDescricao.setText(p.getDescricao());  
    }   
    
 /*   public void preencheCargo(int Numero){
       jTxtNumero.setText(String.valueOf(Numero));
       jTxtDescricao.requestFocusInWindow(); 
    }*/
    
    private void limpar() {
         JTextField txt[] = {jTxtCodigo, jTxtDescricao};
        for (JTextField t : txt)
            t.setText(""); 
        jTxtCodigo.setEditable(true); 
       jBtnIncluir.setEnabled(false);
       jBtnAlterar.setEnabled(false);
       jBtnExcluir.setEnabled(false);
      jTxtDescricao.requestFocusInWindow();
    }       
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCodigo = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLblDescricao = new javax.swing.JLabel();
        jTxtDescricao = new javax.swing.JTextField();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblCodigo.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblCodigo.setText("Codigo");
        getContentPane().add(jLblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 34, -1, 21));

        jTxtCodigo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigoFocusLost(evt);
            }
        });
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 28, 89, 27));

        jLblDescricao.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblDescricao.setText("Descricao");
        getContentPane().add(jLblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 71, -1, 28));

        jTxtDescricao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtDescricaoKeyReleased(evt);
            }
        });
        getContentPane().add(jTxtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 71, 241, 28));

        jPnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnIncluir.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnRetornar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnRetornar.setText("Retornar");
        jBtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBtnIncluir)
                .addGap(12, 12, 12)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExcluir)
                .addGap(12, 12, 12)
                .addComponent(jBtnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRetornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnLimpar)
                    .addComponent(jBtnRetornar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, -1, -1));

        setSize(new java.awt.Dimension(445, 202));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jBtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRetornarActionPerformed
// TODO add your handling code here:
     if (Diversos.confirmar("Deseja retornar?", titulo))
        dispose();
}//GEN-LAST:event_jBtnRetornarActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
   jTxtDescricao.requestFocusInWindow(); 
}//GEN-LAST:event_formWindowActivated

private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
// TODO add your handling code here:
   limpar();
}//GEN-LAST:event_jBtnLimparActionPerformed

private void jTxtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigoFocusLost
// TODO add your handling code here:
    int codigo; 
    Object o; 
    Projeto p;
     if(!Diversos.testaNum(jTxtCodigo.getText(), titulo))
         jTxtCodigo.setText("");
     else if (!Diversos.intervalo(Integer.parseInt(jTxtCodigo.getText()), 0, 0, titulo))
               jTxtCodigo.setText("");
            else {
                    codigo = Integer.parseInt(jTxtCodigo.getText());
                    o = cP.getBusca(codigo,0);
                   if (o == null) {
                      jBtnIncluir.setEnabled(true);
                      Diversos.mostrarDados("Projeto Inexistente",titulo,false);
                  }    
                  else{ 
                         p = (Projeto) o;                       
                         carregaObjetos(p);
                        jBtnAlterar.setEnabled(true);
                       jBtnExcluir.setEnabled(true);   
                 }                
           }
      jTxtCodigo.setEditable(false);                                          
}//GEN-LAST:event_jTxtCodigoFocusLost

private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
// TODO add your handling code here:
   if (Diversos.confirmar("Deseja remover o projeto ?", titulo)) {
       Object o = cP.getBusca(Integer.parseInt( jTxtCodigo.getText()), 0);
      Projeto p = (Projeto) o;
       if (cP.setManipular(p, 'E')) {
            Diversos.mostrarDados("Cargo " + jTxtDescricao.getText() + 
                  " foi removido com sucesso!!!", titulo, true);
           jBtnLimparActionPerformed(evt);
           jBtnAlterar.setEnabled(false);
           jBtnExcluir.setEnabled(false);            
       }
       else
         Diversos.mostrarDados("Problema ao remover o projeto " + 
                 jTxtDescricao.getText() , titulo, false);
           
    }               
}//GEN-LAST:event_jBtnExcluirActionPerformed

private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
// TODO add your handling code here:
      if (jTxtCodigo.getText().isEmpty() || jTxtDescricao.getText().isEmpty() )
        Diversos.mostrarDados("Preencha todos os dados", titulo, false);
      else {
            Projeto p = new Projeto();
             p.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
             p.setDescricao(jTxtDescricao.getText());
             if (jBtnIncluir.isEnabled()) {
                    if (cP.setManipular(p, 'I')) { //== true
                       Diversos.mostrarDados("O projeto " +
                          jTxtDescricao.getText() + " foi inserido com sucesso", titulo, true);
                       jBtnAlterar.setEnabled(true);
                       jBtnExcluir.setEnabled(true);
                   }
                   else //== false
                         Diversos.mostrarDados("Problemas ao inserir os dados " +
                              "do projeto " + jTxtDescricao.getText(), titulo, false);                       
                 jBtnIncluir.setEnabled(false); 
                 
             }     
             else if (cP.setManipular(p,'A')) 
                        Diversos.mostrarDados("O projeto " + jTxtDescricao.getText() +
                             " foi atualizado(a) com sucesso", titulo, true);              
                    else {
                           Diversos.mostrarDados("Problemas ao atualizar os dados "
                                 + "do projeto " + jTxtDescricao.getText(), titulo, false);                                   
                           jBtnAlterar.setEnabled(false);
                          jBtnExcluir.setEnabled(false);
                   }           
       }
}//GEN-LAST:event_jBtnIncluirActionPerformed

private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
// TODO add your handling code here:
    jBtnIncluirActionPerformed(evt);
}//GEN-LAST:event_jBtnAlterarActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    limpar();
}//GEN-LAST:event_formWindowOpened

    private void jTxtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDescricaoKeyReleased
        // TODO add your handling code here:
        jTxtDescricao.setText(jTxtDescricao.getText().toUpperCase());
    }//GEN-LAST:event_jTxtDescricaoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrmProjeto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnRetornar;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblDescricao;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDescricao;
    // End of variables declaration//GEN-END:variables
}
