/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Controle.ControleBasico;
import Controle.ControleCargo;
import Controle.ControleFuncionario;
import Negocio.Cargo;
import Negocio.Funcionario;
import Util.Diversos;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author aluno
 */
public class JFrmFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form JFrmFuncionario
     */
    final String titulo;
    ControleBasico cF, cC;
    private List<Object> listaC;
    public JFrmFuncionario() {
        this.cF = new ControleFuncionario(); 
        this.cC = new ControleCargo();
        this.listaC = new ArrayList<>();
        titulo = "Cadastro do(a) funcionario(a)";
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLbLMatricula = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnRetornar = new javax.swing.JButton();
        jTxtMatricula = new javax.swing.JTextField();
        jPnlCargo = new javax.swing.JPanel();
        jCmbCargo = new javax.swing.JComboBox();
        jLblN = new javax.swing.JLabel();
        jLblNumero = new javax.swing.JLabel();
        jLblSalario = new javax.swing.JLabel();
        jTxtSalario = new javax.swing.JTextField();
        jPnlAtivo = new javax.swing.JPanel();
        jChkSim = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbLMatricula.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLbLMatricula.setText("Matricula");
        getContentPane().add(jLbLMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 40, -1, -1));

        jLblNome.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblNome.setText("Nome");
        getContentPane().add(jLblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 87, -1, 20));

        jTxtNome.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jTxtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtNomeKeyReleased(evt);
            }
        });
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 83, 379, 30));

        jPnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnIncluir.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnRetornar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnRetornar.setText("Retornar");
        jBtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnIncluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jBtnRetornar)
                .addGap(27, 27, 27))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnRetornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPnlBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 308, 482, -1));

        jTxtMatricula.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jTxtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtMatriculaFocusLost(evt);
            }
        });
        getContentPane().add(jTxtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 34, 106, 30));

        jPnlCargo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Cargo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 14))); // NOI18N
        jPnlCargo.setFont(new java.awt.Font("DejaVu Serif", 3, 14)); // NOI18N

        jCmbCargo.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jCmbCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCmbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCargoActionPerformed(evt);
            }
        });

        jLblN.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblN.setText("N°");

        jLblNumero.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPnlCargoLayout = new javax.swing.GroupLayout(jPnlCargo);
        jPnlCargo.setLayout(jPnlCargoLayout);
        jPnlCargoLayout.setHorizontalGroup(
            jPnlCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCargoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblN)
                .addGap(18, 18, 18)
                .addComponent(jLblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPnlCargoLayout.setVerticalGroup(
            jPnlCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCargoLayout.createSequentialGroup()
                .addComponent(jLblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jPnlCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCmbCargo)
                .addComponent(jLblN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPnlCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 119, 460, -1));

        jLblSalario.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblSalario.setText("Salário");
        getContentPane().add(jLblSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 233, -1, -1));

        jTxtSalario.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jTxtSalario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtSalarioKeyReleased(evt);
            }
        });
        getContentPane().add(jTxtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 226, 114, 31));

        jPnlAtivo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Ativo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 14))); // NOI18N
        jPnlAtivo.setFont(new java.awt.Font("DejaVu Serif", 3, 14)); // NOI18N

        jChkSim.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jChkSim.setText("Sim");
        jChkSim.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jChkSim.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPnlAtivoLayout = new javax.swing.GroupLayout(jPnlAtivo);
        jPnlAtivo.setLayout(jPnlAtivoLayout);
        jPnlAtivoLayout.setHorizontalGroup(
            jPnlAtivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlAtivoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jChkSim)
                .addGap(20, 20, 20))
        );
        jPnlAtivoLayout.setVerticalGroup(
            jPnlAtivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAtivoLayout.createSequentialGroup()
                .addComponent(jChkSim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPnlAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 210, -1, -1));

        setSize(new java.awt.Dimension(506, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void limpar() { 
         JTextField txt[] = {jTxtMatricula, jTxtNome,  jTxtSalario};
        for (JTextField t : txt)
            t.setText("");
        jTxtMatricula.setEditable(true);
        jLblNumero.setText("");
        jCmbCargo.setSelectedIndex(-1);
        buttonGroup.clearSelection();
        jChkSim.setSelected(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnIncluir.setEnabled(false);
        jTxtNome.requestFocusInWindow();
    }
    private void carregaObjetos(Funcionario f) {
       jTxtNome.setText(f.getNome());
       jTxtMatricula.setText(String.valueOf(f.getMatricula()));       
       jLblNumero.setText(String.valueOf(f.getCargo().getNumero()));
       jCmbCargo.setSelectedItem(f.getCargo().getDescricao());
       jTxtSalario.setText(NumberFormat.getNumberInstance().format(f.getSalario()));
       jChkSim.setSelected(f.isAtivo());
    } 
    
     private void carregaLista() {
        int posi = jCmbCargo.getSelectedIndex(); //guarda a posição coorente
        listaC = cC.lista();
       jCmbCargo.removeAllItems();
       for (Object o : listaC) {
            Cargo c = (Cargo) o;
            jCmbCargo.addItem(c.getDescricao());
        }
         if (posi > -1) 
              jCmbCargo.setSelectedIndex(posi);
         else {
            jLblNumero.setText("");
            jCmbCargo.setSelectedIndex(-1);
         }
     }     
    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jBtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRetornarActionPerformed
        // TODO add your handling code here:
        if(Diversos.confirmar("Deseja retornar", titulo))
          dispose();  
    }//GEN-LAST:event_jBtnRetornarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Funcionario f ;
        if(jTxtMatricula.getText().isEmpty() || jTxtNome.getText().isEmpty()) 
           Diversos.mostrarDados("Favor preencher os campos", titulo, false);
        else{  
            f = new Funcionario();
            f.setMatricula(Integer.parseInt(jTxtMatricula.getText()));
            f.setNome(jTxtNome.getText());
            f.setSalario(Float.parseFloat(jTxtSalario.getText().replace(",", ".")));
            Cargo c = new Cargo();
            String cargo = (String) jCmbCargo.getSelectedItem();
            c.setNumero(Integer.parseInt(jLblNumero.getText()));
            c.setDescricao(cargo);
            f.setCargo(c);
            f.setAtivo(jChkSim.isSelected());
            if (jBtnIncluir.isEnabled()) { 
                 if (cF.setManipular(f, 'I')) {
                     Diversos.mostrarDados("Funcionario(a) " + jTxtNome.getText() +
                             " foi inserido(a) com sucesso", titulo, true);
                     jBtnAlterar.setEnabled(true);
                     jBtnExcluir.setEnabled(true);
                 }
                 else 
                     Diversos.mostrarDados("Problemas ao inserir os dados do(a) funcionario(a) " +
                                 jTxtNome.getText(), titulo, false); 
                      
                 jBtnIncluir.setEnabled(false);
            }
            else if (cF.setManipular(f, 'A'))
                      Diversos.mostrarDados("Funcionario(a) " + jTxtNome.getText() +
                            " foi atualizado(a) com sucesso", titulo, true);                    
                  else {
                         Diversos.mostrarDados("Problemas ao atualizar os dados do(a) funcionario(a) " +
                                jTxtNome.getText(), titulo, false); 
                        jBtnAlterar.setEnabled(false);
                         jBtnExcluir.setEnabled(false);
                  }            
            }             
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        jBtnIncluirActionPerformed(evt);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
       if (Diversos.confirmar("Deseja remover o funcionario(a) ", titulo)){
          Object o = cF.getBusca(Integer.parseInt(jTxtMatricula.getText()), 0);
          Funcionario f = (Funcionario) o;  
          if (cF.setManipular(f, 'E')) {
            Diversos.mostrarDados("Funcionario(a) " + jTxtNome.getText() + 
                  " foi removido com sucesso!!!", titulo, true);
           jBtnLimparActionPerformed(evt);
           jBtnAlterar.setEnabled(false);
           jBtnExcluir.setEnabled(false);   
         
       }
       else
         Diversos.mostrarDados("Problema ao remover o cargo " + 
                 jTxtNome.getText() , titulo, false);
      }                         
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTxtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNomeKeyReleased
        // TODO add your handling code here:
         jTxtNome.setText(jTxtNome.getText().toUpperCase());
    }//GEN-LAST:event_jTxtNomeKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_formWindowOpened

    private void jTxtMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtMatriculaFocusLost
        // TODO add your handling code here:
        Object o;
        Funcionario f;
        int matricula;
       
        if (!Diversos.testaNum(jTxtMatricula.getText(), titulo))
              jTxtMatricula.setText("");
        else if (!Diversos.intervalo(Integer.parseInt(jTxtMatricula.getText()) ,0 ,0 , titulo))
                  jTxtMatricula.setText("");
               else {
                      matricula= Integer.parseInt(jTxtMatricula.getText());
                      o =  cF.getBusca(matricula, 0);
                     if (o == null) {
                        jBtnIncluir.setEnabled(true);
                        Diversos.mostrarDados("Funcionario inexistente", titulo, false);
                     }
                else{
                      f = (Funcionario) o;
                      carregaObjetos(f);
                     jBtnAlterar.setEnabled(true);
                     jBtnExcluir.setEnabled(true);
                }
                jTxtMatricula.setEditable(false);
        } 
         
    }//GEN-LAST:event_jTxtMatriculaFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        carregaLista();
        jTxtNome.requestFocusInWindow();
    }//GEN-LAST:event_formWindowActivated

    private void jTxtSalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSalarioKeyReleased
        // TODO add your handling code here:
        if(!Diversos.testaNum(jTxtSalario.getText().replace(",", "."), titulo))
          jTxtSalario.setText("");
        else if(!Diversos.intervalo
            (Float.parseFloat(jTxtSalario.getText().replace(",", ".")), 0, 0, titulo))
        jTxtSalario.setText("");
    }//GEN-LAST:event_jTxtSalarioKeyReleased

    private void jCmbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCargoActionPerformed
        // TODO add your handling code here:
          int ind = jCmbCargo.getSelectedIndex();
          if (ind > -1) {
             Object o = listaC.get(ind);
             Cargo c = (Cargo) o;
            jLblNumero.setText(String.valueOf(c.getNumero()));
          }   
    }//GEN-LAST:event_jCmbCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
         @Override
         public void run() {
                new JFrmFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnRetornar;
    private javax.swing.JCheckBox jChkSim;
    private javax.swing.JComboBox jCmbCargo;
    private javax.swing.JLabel jLbLMatricula;
    private javax.swing.JLabel jLblN;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JLabel jLblSalario;
    private javax.swing.JPanel jPnlAtivo;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JPanel jPnlCargo;
    private javax.swing.JTextField jTxtMatricula;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtSalario;
    // End of variables declaration//GEN-END:variables
}
