/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadAloca.java
 *
 * Created on 22/09/2012, 17:17:10
 */
package Interface;
import Controle.ControleAloca;
import Controle.ControleBasico;
import Controle.ControleProjeto;
import Controle.ControleFuncionario;
import Negocio.Aloca;
import Negocio.Financiado;
import Negocio.Funcionario;
import Negocio.NFinanciado;
import Negocio.NFinanciadoHM;
import Negocio.Projeto;
import Util.Diversos;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author aluno
 */
public class JFrmAloca extends javax.swing.JFrame {

    final String titulo;
    ControleBasico cA, cF, cP; 
    List<Object> listaF;
    List<Object> listaP;
    public JFrmAloca() {
        this.cF = new ControleFuncionario();
        this.cP = new ControleProjeto();
        this.cA = new ControleAloca(); 
        this.listaF = new ArrayList<>();
        this.listaP = new ArrayList<>();
        titulo = "Cadastro de alocação de funcionários em projetos";
        initComponents();
        jFtdData.setFormatterFactory(Diversos.FormatoData(titulo, 0));
        jFtdHora.setFormatterFactory(Diversos.FormatoData(titulo, 2));
        setSize(600, 500);
        setResizable(false);
        setLocationRelativeTo(null);
        try {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
             IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrmAloca.class.getName()).log(Level.SEVERE, null, ex);
          } 
    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    private void carregaObjetos(Aloca a) {
        if (a.isFinanciado()) { 
             Financiado fI = (Financiado) a; 
             jSpnDuracao.setValue(fI.getDuracao());
             jSpnDuracao.setEnabled(true);
           //  jLblSalarioR.setText(NumberFormat.getNumberInstance().format(fI.salarioFinal()));
        }
        else {
               jChkContrato.setEnabled(true);
               NFinanciado nF = (NFinanciado) a;
               if(a.getConstroe().equalsIgnoreCase("Hidrelétrica") || 
                                   a.getConstroe().equalsIgnoreCase("Metrô")) {
                             NFinanciadoHM nFGS = (NFinanciadoHM) nF;  
                            // System.out.println(nFGS.salarioFinal());
               } 
               if (nF.getTipo().equalsIgnoreCase("Celetista"))
                    jChkContrato.setSelected(true);
                else
                    jChkContrato.setSelected(false);
        }     
         jLblMatricula.setText(String.valueOf(a.getFuncionario().getMatricula()));
         jCmbFuncionario.setSelectedItem(a.getFuncionario().getNome());
         jLblCodigo.setText(String.valueOf(a.getProjeto().getCodigo()));
         jCmbProjeto.setSelectedItem(a.getProjeto().getDescricao());
         jTxtDescricao.setText(String.valueOf(a.getDescricao()));
         jCmbConstroe.setSelectedItem(a.getConstroe());
         switch (a.getAssocia()) {
               case 'í' : jRdbHibrida.setSelected(true);
                              break;
               case 'r' : jRdbPrivada.setSelected(true);
                              break; 
               case 'ú' : jRdbPublica.setSelected(true);
         } 
         jFtdData.setText(a.getData());
         jFtdHora.setText(a.getHora());
         jChkSim.setSelected(a.isFinanciado());
         jLblSalarioB.setText
        (NumberFormat.getCurrencyInstance().format(a.getFuncionario().getSalario()));
         jTxtDescricao.requestFocusInWindow();
         jLblSalarioF.setText(NumberFormat.getCurrencyInstance().format
        (a.salarioFinal()));
    }
    
     private void limpar() {
        JLabel label[] =  {jLblMatricula, jLblCodigo,  jLblSalarioB, jLblSalarioF};
        for (JLabel l : label)
           l.setText("");
        JComboBox combo[] = {jCmbFuncionario,  jCmbProjeto,  jCmbConstroe};
        for (JComboBox c : combo) {
           c.setSelectedIndex(-1);
           c.setVisible(true);
        }
        JTextField txt[] = {jTxtFuncAux, jTxtProjAux};
        for (JTextField t : txt) {
            t.setText("");
            t.setVisible(false);
            t.setEditable(false);
        }
        jTxtDescricao.setText("");
        JFormattedTextField form[] ={jFtdData, jFtdHora}; 
        for ( JFormattedTextField f : form)
            f.setText("");
        jSpnDuracao.setValue(1);
        jSpnDuracao.setEnabled(false);
        buttonGroup.clearSelection();
        JCheckBox chk[] = {jChkSim, jChkContrato};
        for (JCheckBox b : chk)
            b.setSelected(false);
        jBtnIncluir.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
       jTxtDescricao.requestFocusInWindow();
    }
     
    private void carregaListas() {
       try {
             jCmbConstroe.removeAllItems();
             jCmbConstroe.addItem("Casas");
             jCmbConstroe.addItem("Edifícios");
             jCmbConstroe.addItem("Ferrovias");
             jCmbConstroe.addItem("HidreLétrica");
             jCmbConstroe.addItem("Metrô");
             jCmbConstroe.addItem("Pontes");
             jCmbConstroe.setSelectedIndex(-1);
            int[] posi = {jCmbFuncionario.getSelectedIndex(),
                                 jCmbProjeto.getSelectedIndex()};
            listaF = cF.lista();  
            jCmbFuncionario.removeAllItems();
           for (Object o : listaF) {
                Funcionario f = (Funcionario) o;
                jCmbFuncionario.addItem(f.getNome());
           }
           if (posi[0] > -1) 
                jCmbFuncionario.setSelectedIndex(posi[0]);
           else {
                 jCmbFuncionario.setSelectedIndex(-1);
                 jLblMatricula.setText("");        
           }    
           listaP = cP.lista();  
           jCmbProjeto.removeAllItems();
           for (Object o : listaP) {
                Projeto p = (Projeto) o;
                jCmbProjeto.addItem(p.getDescricao());
           }
           if (posi[1] > -1)  
                jCmbProjeto.setSelectedIndex(posi[1]);
           else {
                    jCmbProjeto.setSelectedIndex(-1); 
                   jLblCodigo.setText("");                
           }       
       } 
       catch(Exception e) {
            Diversos.mostrarDados("Problemas ao carregar os dados dos funcionários" + 
              " e ou dos projetos " + e.getMessage(), titulo, false); 
       }
    }
    
     private void pesquisa() {
        if (!jLblMatricula.getText().isEmpty() && !jLblCodigo.getText().isEmpty() &&
            jCmbFuncionario.getSelectedIndex() > -1 &&
                jCmbProjeto.getSelectedIndex() > -1) {
            Object o = cA.getBusca(Integer.parseInt(jLblMatricula.getText()),
                    Integer.parseInt(jLblCodigo.getText()));
            Aloca a;
            if (o == null) {
                                  Diversos.mostrarDados("Inexistência de alocação do " + 
                                        jCmbFuncionario.getSelectedItem() + " com o projeto " +
                                        jCmbProjeto.getSelectedItem(), titulo,false); 
                                  jBtnIncluir.setEnabled(true);
            }    
            else { 
                   a = (Aloca) o;
                   carregaObjetos(a);
                   jBtnAlterar.setEnabled(true);
                   jBtnExcluir.setEnabled(true);           
            }
            JTextField txt[] = {jTxtFuncAux, jTxtProjAux};
            for (JTextField t : txt) 
                  t.setVisible(true);
            JComboBox combo[] = {jCmbFuncionario,  jCmbProjeto};
            for (JComboBox c : combo) 
                   c.setVisible(false);
            jTxtDescricao.requestFocusInWindow(); 
        }
     }
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLblMatri = new javax.swing.JLabel();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnRetornar = new javax.swing.JButton();
        jLblMatricula = new javax.swing.JLabel();
        jLblProjeto = new javax.swing.JLabel();
        jCmbProjeto = new javax.swing.JComboBox();
        jLblFuncionario = new javax.swing.JLabel();
        jLblSAlReal = new javax.swing.JLabel();
        jLblSalarioF = new javax.swing.JLabel();
        jLblCod = new javax.swing.JLabel();
        jCmbFuncionario = new javax.swing.JComboBox();
        jLblCodigo = new javax.swing.JLabel();
        jLblDescricao = new javax.swing.JLabel();
        jTxtDescricao = new javax.swing.JTextField();
        jSpnDuracao = new javax.swing.JSpinner();
        jPnlFinanciado = new javax.swing.JPanel();
        jChkSim = new javax.swing.JCheckBox();
        jLblConstruir = new javax.swing.JLabel();
        jCmbConstroe = new javax.swing.JComboBox();
        jPnlTipo = new javax.swing.JPanel();
        jRdbHibrida = new javax.swing.JRadioButton();
        jRdbPrivada = new javax.swing.JRadioButton();
        jRdbPublica = new javax.swing.JRadioButton();
        jLblData = new javax.swing.JLabel();
        jFtdData = new javax.swing.JFormattedTextField();
        jLblHora = new javax.swing.JLabel();
        jFtdHora = new javax.swing.JFormattedTextField();
        jLblSAlBas = new javax.swing.JLabel();
        jLblSalarioB = new javax.swing.JLabel();
        jPnlContrato = new javax.swing.JPanel();
        jChkContrato = new javax.swing.JCheckBox();
        jTxtFuncAux = new javax.swing.JTextField();
        jTxtProjAux = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblMatri.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblMatri.setText("Matrícula");
        getContentPane().add(jLblMatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 35, -1, 20));

        jPnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnIncluir.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        jPnlBotoes.add(jBtnIncluir);

        jBtnAlterar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        jPnlBotoes.add(jBtnAlterar);

        jBtnExcluir.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        jPnlBotoes.add(jBtnExcluir);

        jBtnLimpar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });
        jPnlBotoes.add(jBtnLimpar);

        jBtnRetornar.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jBtnRetornar.setText("Retornar");
        jBtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRetornarActionPerformed(evt);
            }
        });
        jPnlBotoes.add(jBtnRetornar);

        getContentPane().add(jPnlBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 421, 454, 49));

        jLblMatricula.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 30, 40, 30));

        jLblProjeto.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblProjeto.setText("Projeto");
        getContentPane().add(jLblProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 79, -1, -1));

        jCmbProjeto.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jCmbProjeto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCmbProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbProjetoActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, -1));

        jLblFuncionario.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblFuncionario.setText("Funcionário");
        getContentPane().add(jLblFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 96, 27));

        jLblSAlReal.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblSAlReal.setText("Salário real");
        getContentPane().add(jLblSAlReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 381, 103, 30));

        jLblSalarioF.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblSalarioF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblSalarioF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLblSalarioF, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 381, 156, 30));

        jLblCod.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblCod.setText("Código");
        getContentPane().add(jLblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 72, -1, 30));

        jCmbFuncionario.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jCmbFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCmbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, -1));

        jLblCodigo.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 72, 40, 30));

        jLblDescricao.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblDescricao.setText("Descrição");
        getContentPane().add(jLblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 172, -1, -1));

        jTxtDescricao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtDescricaoKeyReleased(evt);
            }
        });
        getContentPane().add(jTxtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 164, 332, 33));

        jSpnDuracao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jSpnDuracao.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpnDuracao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Duração", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 14))); // NOI18N
        getContentPane().add(jSpnDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 343, 117, -1));

        jPnlFinanciado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Financiado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 14))); // NOI18N

        jChkSim.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jChkSim.setText("Sim");
        jChkSim.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jChkSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkSimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlFinanciadoLayout = new javax.swing.GroupLayout(jPnlFinanciado);
        jPnlFinanciado.setLayout(jPnlFinanciadoLayout);
        jPnlFinanciadoLayout.setHorizontalGroup(
            jPnlFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlFinanciadoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jChkSim)
                .addGap(20, 20, 20))
        );
        jPnlFinanciadoLayout.setVerticalGroup(
            jPnlFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFinanciadoLayout.createSequentialGroup()
                .addComponent(jChkSim)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlFinanciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 215, -1, -1));

        jLblConstruir.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblConstruir.setText("Construção");
        getContentPane().add(jLblConstruir, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 128, 96, -1));

        jCmbConstroe.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jCmbConstroe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jCmbConstroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 121, 270, -1));

        jPnlTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tipo de associação", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 14))); // NOI18N

        buttonGroup.add(jRdbHibrida);
        jRdbHibrida.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jRdbHibrida.setText("Híbrida");
        jRdbHibrida.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup.add(jRdbPrivada);
        jRdbPrivada.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jRdbPrivada.setText("Privada");
        jRdbPrivada.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup.add(jRdbPublica);
        jRdbPublica.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jRdbPublica.setText("Pública");
        jRdbPublica.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPnlTipoLayout = new javax.swing.GroupLayout(jPnlTipo);
        jPnlTipo.setLayout(jPnlTipoLayout);
        jPnlTipoLayout.setHorizontalGroup(
            jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRdbHibrida)
                .addGap(26, 26, 26)
                .addComponent(jRdbPrivada)
                .addGap(31, 31, 31)
                .addComponent(jRdbPublica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlTipoLayout.setVerticalGroup(
            jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTipoLayout.createSequentialGroup()
                .addGroup(jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbHibrida)
                    .addComponent(jRdbPrivada)
                    .addComponent(jRdbPublica))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 215, 335, -1));

        jLblData.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblData.setText("Data");
        getContentPane().add(jLblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 298, -1, -1));

        jFtdData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jFtdData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFtdData.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        getContentPane().add(jFtdData, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 293, 90, 27));

        jLblHora.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblHora.setText("Hora");
        getContentPane().add(jLblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 297, -1, 20));

        jFtdHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jFtdHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        jFtdHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFtdHora.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        getContentPane().add(jFtdHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 60, 27));

        jLblSAlBas.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLblSAlBas.setText("Salário básico ");
        getContentPane().add(jLblSAlBas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 120, 30));

        jLblSalarioB.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblSalarioB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblSalarioB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLblSalarioB, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 341, 156, 30));

        jPnlContrato.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Contrato", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 14))); // NOI18N

        jChkContrato.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jChkContrato.setText("Celetista");
        jChkContrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jChkContrato.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPnlContratoLayout = new javax.swing.GroupLayout(jPnlContrato);
        jPnlContrato.setLayout(jPnlContratoLayout);
        jPnlContratoLayout.setHorizontalGroup(
            jPnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlContratoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jChkContrato)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPnlContratoLayout.setVerticalGroup(
            jPnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlContratoLayout.createSequentialGroup()
                .addComponent(jChkContrato)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 280, -1, -1));

        jTxtFuncAux.setEditable(false);
        jTxtFuncAux.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtFuncAux.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFuncAux.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTxtFuncAux, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, 30));

        jTxtProjAux.setEditable(false);
        jTxtProjAux.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtProjAux.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtProjAux.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTxtProjAux, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, 30));

        setSize(new java.awt.Dimension(501, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jBtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRetornarActionPerformed
    if (Diversos.confirmar("Deseja Retornar", titulo))
       dispose();
}//GEN-LAST:event_jBtnRetornarActionPerformed

private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
    limpar();
}//GEN-LAST:event_jBtnLimparActionPerformed

private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
// TODO add your handling code here:
    jBtnIncluirActionPerformed(evt);    
}//GEN-LAST:event_jBtnAlterarActionPerformed

private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
     // TODO add your handling code here:
      if (jCmbConstroe.getSelectedIndex() == -1 || jTxtDescricao.getText().isEmpty() ||
          (!jRdbHibrida.isSelected() && !jRdbPrivada.isSelected() && 
              !jRdbPublica.isSelected())) 
          Diversos.mostrarDados("Favor prencher todos os dados", titulo, false);
      else {
           Aloca a ;
           String cons = (String)jCmbConstroe.getSelectedItem();
           if (jChkSim.isSelected()) { 
              Financiado fI = new Financiado();
              fI.setDuracao((int) jSpnDuracao.getValue());
              a = fI;              
           }
           else {
                NFinanciado nF;
                if (cons.equalsIgnoreCase("Hidrelétrica") ||
                            cons.equalsIgnoreCase("Metrô")) {
                    NFinanciadoHM nFHM = new NFinanciadoHM();
                    nF = nFHM;
                }
                 else
                         nF = new NFinanciado();
                 nF.setTipo
                        (jChkContrato.isSelected() ? "Celetista" : "Contratado");
                a = nF;                                  
           }   
           Object o = cF.getBusca(Integer.parseInt(jLblMatricula.getText()), 0);
           Funcionario f =  (Funcionario) o;
           a.setFuncionario(f);
           o = cP.getBusca(Integer.parseInt(jLblCodigo.getText()), 0);
           Projeto p = (Projeto) o;
           a.setProjeto(p);
           a.setDescricao(jTxtDescricao.getText());
           a.setConstroe(cons);
           a.setAssocia(jRdbHibrida.isSelected() ? 'í' :  jRdbPrivada.isSelected() ? 'r' : 'ú');
           a.setData(jFtdData.getText());
           a.setHora(jFtdHora.getText());
           a.setFinanciado(jChkSim.isSelected());
           jLblSalarioB.setText(NumberFormat.getCurrencyInstance().format
                                                         (a.getFuncionario().getSalario()));
           jLblSalarioF.setText(NumberFormat.getCurrencyInstance().format
                                                         (a.salarioFinal()));
           if (jBtnIncluir.isEnabled()) { 
                 if (cA.setManipular(a, 'I')) {
                     Diversos.mostrarDados("A alocação do projeto " + 
                             a.getProjeto().getDescricao() + " com o funcionário " +
                             a.getFuncionario().getNome() + " foi inserido com sucesso", 
                             titulo, true);
                       jBtnAlterar.setEnabled(true);
                       jBtnExcluir.setEnabled(true);                    
                 }
                 else 
                     Diversos.mostrarDados
                     ("Problemas ao inserir os dados da alocação do projeto " +
                     a.getProjeto().getDescricao() + " com o funcionario " +
                     a.getFuncionario().getNome(), titulo, false); 
                jBtnIncluir.setEnabled(false);                
           }
           else if (cA.setManipular(a, 'A'))
                     Diversos.mostrarDados("A alocação do projeto " + 
                     a.getProjeto().getDescricao() +
                     " com o funcionário " + a.getFuncionario().getNome() + 
                     " foi atualizado com sucesso", titulo, true);                    
                 else {
                         Diversos.mostrarDados
                         ("Problemas ao atualizar os dados da alocação do projeto " +
                         a.getProjeto().getDescricao() + " com o  funcionário " + 
                         a.getFuncionario().getNome(), titulo, false);                                   
                         jBtnAlterar.setEnabled(false);
                         jBtnExcluir.setEnabled(false);                 
                  }  
        }                                                                                   
}//GEN-LAST:event_jBtnIncluirActionPerformed

private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
// TODO add your handling code here:       
     if (Diversos.confirmar("Deseja remover a alocação", titulo)) {
        Object o = cA.getBusca(Integer.parseInt(jLblMatricula.getText()) , 
                                                Integer.parseInt(jLblCodigo.getText()));
       Aloca a = (Aloca) o;  
       if (cA.setManipular(a, 'E')) {
           Diversos.mostrarDados("A alocação do projeto " + 
              a.getProjeto().getDescricao() + " com o funcionário " +
              a.getFuncionario().getNome() + " foi removido com sucesso", titulo, true);  
           jBtnLimparActionPerformed(evt);
           jBtnAlterar.setEnabled(false);
           jBtnExcluir.setEnabled(false);        
       }
       else
         Diversos.mostrarDados("Problemas ao remover os dados da alocação do projeto " 
                 + a.getProjeto().getDescricao() + " com o funcionário " +
                      a.getFuncionario().getNome(), titulo, false);     
    }                   
}//GEN-LAST:event_jBtnExcluirActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
     carregaListas();
     limpar();          
}//GEN-LAST:event_formWindowOpened

    private void jCmbProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbProjetoActionPerformed
        // TODO add your handling code here:
       int ind = jCmbProjeto.getSelectedIndex();
       if (ind > -1) {
            Object o = listaP.get(ind);
            Projeto p = (Projeto) o;
            jTxtProjAux.setText(p.getDescricao());
            jLblCodigo.setText(String.valueOf(p.getCodigo()));
            pesquisa();                  
       }   
    }//GEN-LAST:event_jCmbProjetoActionPerformed

    private void jCmbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbFuncionarioActionPerformed
        // TODO add your handling code here:
        int ind = jCmbFuncionario.getSelectedIndex();
        if (ind > -1) {
            Object o = listaF.get(ind);
            Funcionario f = (Funcionario) o;
            jTxtFuncAux.setText(f.getNome());
            jLblMatricula.setText(String.valueOf(f.getMatricula()));
            jLblSalarioB.setText(NumberFormat.getCurrencyInstance().format
                                             (f.getSalario()));
            pesquisa();
        }
    }//GEN-LAST:event_jCmbFuncionarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
           jTxtDescricao.requestFocusInWindow();      
    }//GEN-LAST:event_formWindowActivated

    private void jTxtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDescricaoKeyReleased
        // TODO add your handling code here:
        jTxtDescricao.setText(jTxtDescricao.getText().toUpperCase());
    }//GEN-LAST:event_jTxtDescricaoKeyReleased

    private void jChkSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkSimActionPerformed
        // TODO add your handling code here:
        if (jChkSim.isSelected()) {
            jSpnDuracao.setEnabled(true);
            jChkContrato.setEnabled(false);
        }
        else {
                jSpnDuracao.setEnabled(false);
               jChkContrato.setEnabled(true);
        }
    }//GEN-LAST:event_jChkSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFrmAloca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnRetornar;
    private javax.swing.JCheckBox jChkContrato;
    private javax.swing.JCheckBox jChkSim;
    private javax.swing.JComboBox jCmbConstroe;
    private javax.swing.JComboBox jCmbFuncionario;
    private javax.swing.JComboBox jCmbProjeto;
    private javax.swing.JFormattedTextField jFtdData;
    private javax.swing.JFormattedTextField jFtdHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblCod;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblConstruir;
    private javax.swing.JLabel jLblData;
    private javax.swing.JLabel jLblDescricao;
    private javax.swing.JLabel jLblFuncionario;
    private javax.swing.JLabel jLblHora;
    private javax.swing.JLabel jLblMatri;
    private javax.swing.JLabel jLblMatricula;
    private javax.swing.JLabel jLblProjeto;
    private javax.swing.JLabel jLblSAlBas;
    private javax.swing.JLabel jLblSAlReal;
    private javax.swing.JLabel jLblSalarioB;
    private javax.swing.JLabel jLblSalarioF;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JPanel jPnlContrato;
    private javax.swing.JPanel jPnlFinanciado;
    private javax.swing.JPanel jPnlTipo;
    private javax.swing.JRadioButton jRdbHibrida;
    private javax.swing.JRadioButton jRdbPrivada;
    private javax.swing.JRadioButton jRdbPublica;
    private javax.swing.JSpinner jSpnDuracao;
    private javax.swing.JTextField jTxtDescricao;
    private javax.swing.JTextField jTxtFuncAux;
    private javax.swing.JTextField jTxtProjAux;
    // End of variables declaration//GEN-END:variables
}
