[package]
name = "n-digit-fibonacci-number"
version = "0.1.0"
authors = ["Tomast1337 <vycasnicolas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3"
num-traits = "0.2.14"