/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Controle.ControleBasico;
import Controle.ControleCadastro;
import Negocio.Cadastro;
import Util.Diversos;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author usuario
 */
public class JFrmPublicacao extends javax.swing.JFrame {
     
    /**
     * Creates new form JFrmPublicacao
     */
    
    final String titulo;
    private ControleBasico cC;
    public JFrmPublicacao() {
       this.titulo = "Livraria publicações";
       this.cC = new ControleCadastro();
        initComponents();
        jFTFData.setFormatterFactory(Diversos.FormatoData(titulo, 0));
        try {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
             IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrmPublicacao.class.getName()).log(Level.SEVERE, null, ex);
          }          
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void limpar() {
        JTextField txt[] = {jTxtCodigo, jTxtTitulo, jTxtPercent,
        jTxtPrecoB, jFTFData};
        for (JTextField t : txt)
            t.setText("");
        JLabel label[] =  {jLblIdent, jLblPrecoF};
        for (JLabel l : label)
           l.setText("");
        jCmbCategoria.setSelectedIndex(-1);
        jTxtCodigo.setEditable(true);
        jTxtARelatorio.setText("");
        buttonGroup.clearSelection();
        jChkSim.setSelected(false);
        jChkSimIN.setSelected(false);
        jTxtPercent.setEditable(false);
        jSpnEdicao.setEnabled(false);
        jChkSimIN.setEnabled(false);
        jBtnIncluir.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jTxtTitulo.requestFocusInWindow();
    }
    @SuppressWarnings("unchecked")
    
    private void carregaObjetos(Cadastro c) {
        switch (c.getTipo()) {//pago == true
            case 'C':jRdbCD.setSelected(true);
            case 'L':jRdbLivro.setSelected(true);
            case 'R':jRdbRevista.setSelected(true);
         }     
       jTxtCodigo.setText(String.valueOf(c.getCodigo()));
       jTxtTitulo.setText(c.getTitulo());
       jCmbCategoria.setSelectedItem(c.getCategoria());
       jTxtPercent.setText(NumberFormat.getNumberInstance().format(c.getPercentual())); 
       jSpnEdicao.setValue(c.getEdicao());
       jFTFData.setText(c.getData());
       jChkSim.setSelected(c.isTraduzido());
       jChkSimIN.setSelected(c.isNacional());
       jTxtPrecoB.setText(NumberFormat.getNumberInstance().format(c.getPrecoB()));
       jLblPrecoF.setText(NumberFormat.getCurrencyInstance().format(c.precoF()));   
       jTxtTitulo.requestFocusInWindow();
       
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jScPPerc = new javax.swing.JScrollPane();
        jTxtARelatorio = new javax.swing.JTextArea();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnRetornar = new javax.swing.JButton();
        jBtnListar = new javax.swing.JButton();
        jLblCodigo = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLblTitulo = new javax.swing.JLabel();
        jTxtTitulo = new javax.swing.JTextField();
        jCmbCategoria = new javax.swing.JComboBox();
        jPnlTipo = new javax.swing.JPanel();
        jRdbCD = new javax.swing.JRadioButton();
        jRdbLivro = new javax.swing.JRadioButton();
        jRdbRevista = new javax.swing.JRadioButton();
        jLblEdicao = new javax.swing.JLabel();
        jLblPer = new javax.swing.JLabel();
        jPnlIN = new javax.swing.JPanel();
        jChkSimIN = new javax.swing.JCheckBox();
        jTxtPercent = new javax.swing.JTextField();
        jSpnEdicao = new javax.swing.JSpinner();
        jLblData = new javax.swing.JLabel();
        jFTFData = new javax.swing.JFormattedTextField();
        jLblId = new javax.swing.JLabel();
        jLblIdent = new javax.swing.JLabel();
        jLblPreco = new javax.swing.JLabel();
        jTxtPrecoB = new javax.swing.JTextField();
        jLblPF = new javax.swing.JLabel();
        jLblPrecoF = new javax.swing.JLabel();
        jPnlTraduzido = new javax.swing.JPanel();
        jChkSim = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTxtARelatorio.setColumns(20);
        jTxtARelatorio.setRows(5);
        jTxtARelatorio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Lista", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 12))); // NOI18N
        jScPPerc.setViewportView(jTxtARelatorio);

        jPnlBotoes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jBtnIncluir.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnRetornar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnRetornar.setText("Sair");
        jBtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRetornarActionPerformed(evt);
            }
        });

        jBtnListar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnListar.setToolTipText("Listar");

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnRetornar)
                        .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnIncluir)
                            .addComponent(jBtnAlterar)
                            .addComponent(jBtnExcluir)
                            .addComponent(jBtnLimpar))))
                .addGap(21, 21, 21))
        );

        jLblCodigo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblCodigo.setText("Codigo");

        jTxtCodigo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigoFocusLost(evt);
            }
        });

        jLblTitulo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblTitulo.setText("Titulo");

        jTxtTitulo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtTituloKeyReleased(evt);
            }
        });

        jCmbCategoria.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jCmbCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Categoria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 12))); // NOI18N
        jCmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCategoriaActionPerformed(evt);
            }
        });

        jPnlTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tipo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 12))); // NOI18N
        jPnlTipo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N

        buttonGroup.add(jRdbCD);
        jRdbCD.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jRdbCD.setText("CD");
        jRdbCD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRdbCD.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRdbCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbCDActionPerformed(evt);
            }
        });

        buttonGroup.add(jRdbLivro);
        jRdbLivro.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jRdbLivro.setText("Livro");
        jRdbLivro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRdbLivro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRdbLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbLivroActionPerformed(evt);
            }
        });

        buttonGroup.add(jRdbRevista);
        jRdbRevista.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jRdbRevista.setText("Revista");
        jRdbRevista.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRdbRevista.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRdbRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbRevistaActionPerformed(evt);
            }
        });

        jLblEdicao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblEdicao.setText("Edição N°");

        jLblPer.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblPer.setText("Percentual");

        jPnlIN.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Nacional", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 12))); // NOI18N

        jChkSimIN.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jChkSimIN.setText("Sim");
        jChkSimIN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPnlINLayout = new javax.swing.GroupLayout(jPnlIN);
        jPnlIN.setLayout(jPnlINLayout);
        jPnlINLayout.setHorizontalGroup(
            jPnlINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlINLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChkSimIN)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPnlINLayout.setVerticalGroup(
            jPnlINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChkSimIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTxtPercent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtPercent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSpnEdicao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jSpnEdicao.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpnEdicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPnlTipoLayout = new javax.swing.GroupLayout(jPnlTipo);
        jPnlTipo.setLayout(jPnlTipoLayout);
        jPnlTipoLayout.setHorizontalGroup(
            jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlTipoLayout.createSequentialGroup()
                        .addComponent(jRdbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblPer)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlTipoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jRdbCD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPnlIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlTipoLayout.createSequentialGroup()
                        .addComponent(jRdbRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblEdicao)
                        .addGap(18, 18, 18)
                        .addComponent(jSpnEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPnlTipoLayout.setVerticalGroup(
            jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlTipoLayout.createSequentialGroup()
                .addGroup(jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlTipoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jRdbCD))
                    .addGroup(jPnlTipoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPnlIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbLivro)
                    .addComponent(jLblPer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpnEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRdbRevista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLblData.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblData.setText("Data da publicação");

        jFTFData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jFTFData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTFData.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N

        jLblId.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblId.setText("Identificação");

        jLblIdent.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblIdent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblIdent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLblPreco.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblPreco.setText("Preço Base R$");

        jTxtPrecoB.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtPrecoB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtPrecoB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtPrecoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPrecoBKeyReleased(evt);
            }
        });

        jLblPF.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblPF.setText("Preço Real");

        jLblPrecoF.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblPrecoF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPrecoF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPnlTraduzido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Traduzido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 12))); // NOI18N

        jChkSim.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jChkSim.setText("Sim");
        jChkSim.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPnlTraduzidoLayout = new javax.swing.GroupLayout(jPnlTraduzido);
        jPnlTraduzido.setLayout(jPnlTraduzidoLayout);
        jPnlTraduzidoLayout.setHorizontalGroup(
            jPnlTraduzidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlTraduzidoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jChkSim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPnlTraduzidoLayout.setVerticalGroup(
            jPnlTraduzidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChkSim)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLblTitulo)
                        .addGap(34, 34, 34)
                        .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPnlTraduzido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(jLblIdent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jLblId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLblCodigo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jCmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jFTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtPrecoB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLblPF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblPrecoF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScPPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jPnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLblIdent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLblId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLblCodigo))
                    .addComponent(jCmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPnlTraduzido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLblData))
                    .addComponent(jFTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtPrecoB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblPreco)
                        .addComponent(jLblPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblPrecoF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScPPerc, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(657, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPrecoBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPrecoBKeyReleased
        // TODO add your handling code here:
        if(!Diversos.testaNum(jTxtPrecoB.getText().replace(",", "."), titulo))
        jTxtPrecoB.setText("");
        else if(!Diversos.intervalo
            (Float.parseFloat(jTxtPrecoB.getText().replace(",", ".")), 0, 0, titulo))
        jTxtPrecoB.setText("");
    }//GEN-LAST:event_jTxtPrecoBKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         jTxtTitulo.requestFocusInWindow();
    }//GEN-LAST:event_formWindowActivated

    private void jTxtTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTituloKeyReleased
        // TODO add your handling code here:
        jTxtTitulo.setText(jTxtTitulo.getText().toUpperCase());
    }//GEN-LAST:event_jTxtTituloKeyReleased

    private void jRdbCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbCDActionPerformed
        // TODO add your handling code here:
        jChkSimIN.setEnabled(true);
        jTxtPercent.setEditable(false);
        jSpnEdicao.setEnabled(false);        
    }//GEN-LAST:event_jRdbCDActionPerformed

    private void jRdbLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbLivroActionPerformed
        // TODO add your handling code here:
        jChkSimIN.setEnabled(false);
        jTxtPercent.setEditable(true);
        jSpnEdicao.setEnabled(false);        
    }//GEN-LAST:event_jRdbLivroActionPerformed

    private void jRdbRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbRevistaActionPerformed
        // TODO add your handling code here:
        jChkSimIN.setEnabled(false);
        jTxtPercent.setEditable(false);
        jSpnEdicao.setEnabled(true);
    }//GEN-LAST:event_jRdbRevistaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       jCmbCategoria.addItem("Infantil");
       jCmbCategoria.addItem("Bibliográfico");
       jCmbCategoria.addItem("Didático");
       jCmbCategoria.addItem("Literário");
       jCmbCategoria.addItem("Técnico");
        limpar();
    }//GEN-LAST:event_formWindowOpened

    private void jBtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRetornarActionPerformed
        // TODO add your handling code here:
        if(Diversos.confirmar("Deseja finalizar", titulo))
          System.exit(0);
    }//GEN-LAST:event_jBtnRetornarActionPerformed

    private void jCmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbCategoriaActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        if (jTxtCodigo.getText().isEmpty() || jTxtTitulo.getText().isEmpty() ||
            jCmbCategoria.getSelectedIndex() < 0 || jTxtPrecoB.getText().isEmpty() ||
            jTxtPercent.getText().isEmpty() ||
            (!jRdbCD.isSelected() && !jRdbLivro.isSelected() && 
            !jRdbRevista.isSelected())) 
            Diversos.mostrarDados("Favor digitar todos os dados", titulo, false);
        else{
            String categoria = (String) jCmbCategoria.getSelectedItem();
            Cadastro c = new Cadastro();
            c.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
            c.setTitulo(jTxtTitulo.getText());
            c.setPrecoB(Float.parseFloat(jTxtPrecoB.getText().replace(',', '.')));
            c.setPercentual(Float.parseFloat(jTxtPercent.getText().replace(',','.'))/100);
            c.setData(jFTFData.getText());
            c.setCategoria(categoria);
            c.setTipo(jRdbCD.isSelected() ? 'C' : jRdbLivro.isSelected() ? 'L' : 'R');
            c.setEdicao((int)jSpnEdicao.getValue());
            c.setTraduzido(jChkSim.isSelected());
            c.setNacional(jChkSimIN.isSelected());
            if (jBtnIncluir.isEnabled()){
                if(cC.setManipular(c, 'I')){
                Diversos.mostrarDados("O Cadastro " + 
                 jTxtTitulo.getText() + " foi inserido com sucesso ",
                        titulo, true);
                jBtnAlterar.setEnabled(true);
                jBtnExcluir.setEnabled(true);
            }
                 else // ==false
                    Diversos.mostrarDados("Problema ao inserir os dados " + "do Cadastro  " + 
                            jTxtTitulo.getText() , titulo, false);
            jBtnIncluir.setEnabled(false);
            }
            else if(cC.setManipular(c, 'A'))
                Diversos.mostrarDados("O Cadastro " + jTxtTitulo.getText() +
                 " atualizado com sucesso ",titulo, true);
            else {
                Diversos.mostrarDados("Problema ao atualizar os dados " + " do Cadastro " +
                        jTxtTitulo.getText(), titulo, false);
                jBtnAlterar.setEnabled(false);
                jBtnExcluir.setEnabled(false);
            }
            jLblPrecoF.setText(
                    NumberFormat.getCurrencyInstance().format(c.precoF()));
        }
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        jBtnIncluirActionPerformed(evt);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Diversos.confirmar("Deseja remover", titulo)) {
           Object o = cC.getBusca(Integer.parseInt(jTxtCodigo.getText()), 0);
           Cadastro c = (Cadastro) o;
           if (cC.setManipular(c, 'E')) {// == true
                Diversos.mostrarDados("Cadastro "+ jTxtTitulo.getText() + 
                    " removido com sucesso", titulo, true);
               jBtnLimparActionPerformed(evt);
               jBtnAlterar.setEnabled(false);
               jBtnExcluir.setEnabled(false);
           } 
           else 
               Diversos.mostrarDados("Problemas ao remover o cadastro(a) "
                    + jTxtTitulo.getText(), titulo, false);         
        }          
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jTxtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigoFocusLost
        // TODO add your handling code here:
        Object o;
         int numero;
         Cadastro c;
        
        if (!Diversos.testaNum(jTxtCodigo.getText(), titulo))
              jTxtCodigo.setText(""); // converter texto para numero
         else{
            numero = Integer.parseInt(jTxtCodigo.getText());
            if (!Diversos.intervalo(numero ,0 ,0 , titulo))
                  jTxtCodigo.setText(""); //testar se é maior que zero
            else {
                   o =  cC.getBusca(numero, 0);
                   if (o == null) { 
                           jBtnIncluir.setEnabled(true);
                          Diversos.mostrarDados("Cadastro n° " + numero + 
                                                              " inexistente", titulo, true);
                 }
                 else {
                    c = (Cadastro) o;  
                    carregaObjetos(c);
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
               }
                jTxtCodigo.setEditable(false);
            }
    }                              
    }//GEN-LAST:event_jTxtCodigoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPublicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPublicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPublicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPublicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPublicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnListar;
    private javax.swing.JButton jBtnRetornar;
    private javax.swing.JCheckBox jChkSim;
    private javax.swing.JCheckBox jChkSimIN;
    private javax.swing.JComboBox jCmbCategoria;
    private javax.swing.JFormattedTextField jFTFData;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblData;
    private javax.swing.JLabel jLblEdicao;
    private javax.swing.JLabel jLblId;
    private javax.swing.JLabel jLblIdent;
    private javax.swing.JLabel jLblPF;
    private javax.swing.JLabel jLblPer;
    private javax.swing.JLabel jLblPreco;
    private javax.swing.JLabel jLblPrecoF;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JPanel jPnlIN;
    private javax.swing.JPanel jPnlTipo;
    private javax.swing.JPanel jPnlTraduzido;
    private javax.swing.JRadioButton jRdbCD;
    private javax.swing.JRadioButton jRdbLivro;
    private javax.swing.JRadioButton jRdbRevista;
    private javax.swing.JScrollPane jScPPerc;
    private javax.swing.JSpinner jSpnEdicao;
    private javax.swing.JTextArea jTxtARelatorio;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtPercent;
    private javax.swing.JTextField jTxtPrecoB;
    private javax.swing.JTextField jTxtTitulo;
    // End of variables declaration//GEN-END:variables
}
