/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cadastro_2.java
 *
 * Created on 15/09/2012, 14:24:10
 */
package Interface;

/**
 *
 * @author aluno
 */
import Controle.ControleBasico;
import Controle.ControleCargo;
import Negocio.Cargo;
import Util.Diversos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class JFrmCargo extends javax.swing.JFrame {

    ControleBasico cS;
    final String titulo;
  
    public JFrmCargo() {
        this.cS = new ControleCargo();
        this.titulo =  "Manipulação do cargo";
        initComponents();
        setSize(450, 250);
        setResizable(false);
        setLocationRelativeTo(null);
        try {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
             IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrmCargo.class.getName()).log(Level.SEVERE, null, ex);
          }   
    }
     
    private void carregaObjetos(Cargo c){
       jTxtNumero.setText(String.valueOf(c.getNumero()));
       jCmbDescricao.setSelectedItem(c.getDescricao());  
    }   
    
     private void limpar() {
       jTxtNumero.setText("");
       jCmbDescricao.setSelectedIndex(-1); 
       jTxtNumero.setEditable(true); 
       jBtnIncluir.setEnabled(false);
       jBtnAlterar.setEnabled(false);
       jBtnExcluir.setEnabled(false);
       jCmbDescricao.requestFocusInWindow();
    }       
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNumero = new javax.swing.JLabel();
        jTxtNumero = new javax.swing.JTextField();
        jLblDefinicao = new javax.swing.JLabel();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnRetornar = new javax.swing.JButton();
        jCmbDescricao = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblNumero.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblNumero.setText("Número");
        getContentPane().add(jLblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, 30));

        jTxtNumero.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtNumeroFocusLost(evt);
            }
        });
        getContentPane().add(jTxtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 89, 27));

        jLblDefinicao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblDefinicao.setText("Definição");
        getContentPane().add(jLblDefinicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 28));

        jPnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnIncluir.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnRetornar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnRetornar.setText("Retornar");
        jBtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBtnIncluir)
                .addGap(26, 26, 26)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnLimpar)
                .addGap(18, 18, 18)
                .addComponent(jBtnRetornar)
                .addContainerGap())
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnLimpar)
                    .addComponent(jBtnRetornar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 420, -1));

        jCmbDescricao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jCmbDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jCmbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, -1));

        setSize(new java.awt.Dimension(445, 202));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jBtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRetornarActionPerformed
// TODO add your handling code here:
     if (Diversos.confirmar("Deseja retornar", titulo))
        dispose();
}//GEN-LAST:event_jBtnRetornarActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
   jCmbDescricao.requestFocusInWindow(); 
}//GEN-LAST:event_formWindowActivated

private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
// TODO add your handling code here:
   limpar();
}//GEN-LAST:event_jBtnLimparActionPerformed

private void jTxtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNumeroFocusLost
// TODO add your handling code here:
    int codigo; 
    Object o; 
    Cargo s;
     if(!Diversos.testaNum(jTxtNumero.getText(), titulo))
         jTxtNumero.setText("");
     else if (!Diversos.intervalo(Integer.parseInt(jTxtNumero.getText()), 0, 0, titulo))
               jTxtNumero.setText("");
            else {
                    codigo = Integer.parseInt(jTxtNumero.getText());
                    o = cS.getBusca(codigo,0);
                    if (o == null) {
                      jBtnIncluir.setEnabled(true);
                      Diversos.mostrarDados("Cargo inexistente",titulo,false);
                  }    
                  else{ 
                        s = (Cargo) o;                       
                        carregaObjetos(s);
                        jBtnAlterar.setEnabled(true);
                        jBtnExcluir.setEnabled(true);   
                 }                
           }
      jTxtNumero.setEditable(false);                                          
}//GEN-LAST:event_jTxtNumeroFocusLost

private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
// TODO add your handling code here:
   if (Diversos.confirmar("Deseja remover o cargo", titulo)) {
       Object o = cS.getBusca(Integer.parseInt( jTxtNumero.getText()), 0);
       Cargo s = (Cargo) o;  
       if (cS.setManipular(s, 'E')) {
            Diversos.mostrarDados("Cargo " + jCmbDescricao.getSelectedItem() + 
                  " foi removido com sucesso!!!", titulo, true);
           jBtnLimparActionPerformed(evt);
           jBtnAlterar.setEnabled(false);
           jBtnExcluir.setEnabled(false);            
       }
       else
         Diversos.mostrarDados("Problemas ao remover o cargo " + 
                 jCmbDescricao.getSelectedItem() , titulo, false);
           
    }               
}//GEN-LAST:event_jBtnExcluirActionPerformed

private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
// TODO add your handling code here:
      if (jTxtNumero.getText().isEmpty() || jCmbDescricao.getSelectedIndex() < 0 )
        Diversos.mostrarDados("Preencha todos os dados", titulo, false);
      else {
             Cargo c= new Cargo();
             c.setNumero(Integer.parseInt(jTxtNumero.getText()));
             c.setDescricao((String)jCmbDescricao.getSelectedItem());
             if (jBtnIncluir.isEnabled()) {
                    if (cS.setManipular(c, 'I')) { //== true
                       Diversos.mostrarDados("O cargo " +
                          jCmbDescricao.getSelectedItem() + " foi inserido com sucesso", titulo, true);
                       jBtnAlterar.setEnabled(true);
                       jBtnExcluir.setEnabled(true);
                   }
                   else //== false
                         Diversos.mostrarDados("Problemas ao inserir os dados " +
                              "do cargo " + jCmbDescricao.getSelectedItem(), titulo, false);                       
                 jBtnIncluir.setEnabled(false); 
                 
             }     
             else if (cS.setManipular(c,'A')) 
                        Diversos.mostrarDados("O cargo " + jCmbDescricao.getSelectedItem() +
                             " foi atualizada com sucesso", titulo, true);              
                    else {
                           Diversos.mostrarDados("Problemas ao atualizar os dados "
                                 + "do cargo " + jCmbDescricao.getSelectedItem(), titulo, false);                                   
                           jBtnAlterar.setEnabled(false);
                          jBtnExcluir.setEnabled(false);
                   }           
       }
}//GEN-LAST:event_jBtnIncluirActionPerformed

private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
// TODO add your handling code here:
    jBtnIncluirActionPerformed(evt);
}//GEN-LAST:event_jBtnAlterarActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    jCmbDescricao.removeAllItems();
    jCmbDescricao.addItem("Almoxarife");
    jCmbDescricao.addItem("Engenheiro");
    jCmbDescricao.addItem("Gerente");
    jCmbDescricao.addItem("Secretária(o)");
    jCmbDescricao.addItem("Supervisor");
    jCmbDescricao.addItem("Técnico");
    jCmbDescricao.setSelectedIndex(-1);
    limpar();
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFrmCargo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnRetornar;
    private javax.swing.JComboBox jCmbDescricao;
    private javax.swing.JLabel jLblDefinicao;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JTextField jTxtNumero;
    // End of variables declaration//GEN-END:variables
}
