/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;



import Controle.ControleBasico;
import Controle.ControleCargo;
import Controle.ControleContratado;
import Controle.ControleFuncionarioDRH;
import Util.Diversos;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author aluno
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jFrmPrincipalS
     */
    private final String titulo;
    private ControleBasico cC, cCO, cA, cF; 
    public JFrmPrincipal() {
        titulo = "Contratos dos contratos";
        criaTabelas();
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
          }     
        
    }
    
    
    private void relogio(){
       try{
           Thread.sleep(1000);
           while(true){
              Date hoje = new Date();
              long hora = hoje.getTime();
              DateFormat dH = DateFormat.getTimeInstance();
              jLblHora.setText("  Hora : " + dH.format(hora));
           }                   
       } 
       catch (InterruptedException e){
         Diversos.mostrarDados("Problema ao acionar a hora " + e.getMessage(), titulo, false);  
       } 
    }
    
     private void criaTabelas() {
       cA = new ControleCargo();
     //  cC = new ControleContrato();
       cCO = new ControleContratado();
       cF   = new ControleFuncionarioDRH();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTlBDataHora = new javax.swing.JToolBar();
        jLblAutor = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLblData = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLblHora = new javax.swing.JLabel();
        jMBPrincipal = new javax.swing.JMenuBar();
        jMnArquivo = new javax.swing.JMenu();
        jSeparatorA = new javax.swing.JPopupMenu.Separator();
        jMnISair = new javax.swing.JMenuItem();
        jMnConsulta = new javax.swing.JMenu();
        jSeparatorO = new javax.swing.JPopupMenu.Separator();
        jMnCadastro = new javax.swing.JMenu();
        jMnICargo = new javax.swing.JMenuItem();
        jMnIContratado = new javax.swing.JMenuItem();
        jMnIFuncionarioDRH = new javax.swing.JMenuItem();
        jSeparatorC = new javax.swing.JPopupMenu.Separator();
        jMnIContrato = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTlBDataHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTlBDataHora.setRollover(true);
        jTlBDataHora.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N

        jLblAutor.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTlBDataHora.add(jLblAutor);
        jTlBDataHora.add(jSeparator3);
        jTlBDataHora.add(jSeparator4);

        jLblData.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTlBDataHora.add(jLblData);
        jTlBDataHora.add(jSeparator1);
        jTlBDataHora.add(jSeparator2);

        jLblHora.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTlBDataHora.add(jLblHora);

        jMnArquivo.setText("Arquivo");
        jMnArquivo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N

        jSeparatorA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMnArquivo.add(jSeparatorA);

        jMnISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnISair.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jMnISair.setText("Sair");
        jMnISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnISairActionPerformed(evt);
            }
        });
        jMnArquivo.add(jMnISair);

        jMBPrincipal.add(jMnArquivo);

        jMnConsulta.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N

        jSeparatorO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMnConsulta.add(jSeparatorO);

        jMBPrincipal.add(jMnConsulta);

        jMnCadastro.setText("Cadastro");
        jMnCadastro.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N

        jMnICargo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMnICargo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jMnICargo.setText("Cargo");
        jMnICargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnICargoActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnICargo);

        jMnIContratado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMnIContratado.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jMnIContratado.setText("Contratado");
        jMnIContratado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIContratadoActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnIContratado);

        jMnIFuncionarioDRH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMnIFuncionarioDRH.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jMnIFuncionarioDRH.setText("FuncionarioDRH");
        jMnIFuncionarioDRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIFuncionarioDRHActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnIFuncionarioDRH);

        jSeparatorC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMnCadastro.add(jSeparatorC);

        jMnIContrato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnIContrato.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jMnIContrato.setText("Contrato");
        jMnIContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIContratoActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnIContrato);

        jMBPrincipal.add(jMnCadastro);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTlBDataHora, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 252, Short.MAX_VALUE)
                .addComponent(jTlBDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(487, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
          jLblAutor.setText("               Autor : Desconhecido                   ");
         Date hoje = new Date();
         DateFormat dF = DateFormat.getDateInstance();
         jLblData.setText("                                                                Data : " + dF.format(hoje) +
                                      "                                                                                            ");  
    }//GEN-LAST:event_formWindowActivated

    private void jMnISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnISairActionPerformed
        // TODO add your handling code here:
         if (Diversos.confirmar("Deseja realmente finalizar", titulo))
            System.exit(0);
    }//GEN-LAST:event_jMnISairActionPerformed

    private void jMnICargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnICargoActionPerformed
        // TODO add your handling code here:
        JFrmCargo fA = new JFrmCargo();
        fA.setVisible(true);
    }//GEN-LAST:event_jMnICargoActionPerformed

    private void jMnIContratadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIContratadoActionPerformed
        // TODO add your handling code here:
        JFrmContratado fC = new JFrmContratado();
        fC.setVisible(true);
    }//GEN-LAST:event_jMnIContratadoActionPerformed

    private void jMnIFuncionarioDRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIFuncionarioDRHActionPerformed
        // TODO add your handling code here:
        JFrmFuncionarioDRH fF = new JFrmFuncionarioDRH();
        fF.setVisible(true);
    }//GEN-LAST:event_jMnIFuncionarioDRHActionPerformed

    private void jMnIContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIContratoActionPerformed
        // TODO add your handling code here:
        JFrmContrato fC = new JFrmContrato();
        fC.setVisible(true);
    }//GEN-LAST:event_jMnIContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
         //  public void run() {
                JFrmPrincipal p = new JFrmPrincipal();
                p.setVisible(true);
                p.relogio();
        // }
       // });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblAutor;
    private javax.swing.JLabel jLblData;
    private javax.swing.JLabel jLblHora;
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenu jMnArquivo;
    private javax.swing.JMenu jMnCadastro;
    private javax.swing.JMenu jMnConsulta;
    private javax.swing.JMenuItem jMnICargo;
    private javax.swing.JMenuItem jMnIContratado;
    private javax.swing.JMenuItem jMnIContrato;
    private javax.swing.JMenuItem jMnIFuncionarioDRH;
    private javax.swing.JMenuItem jMnISair;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparatorA;
    private javax.swing.JPopupMenu.Separator jSeparatorC;
    private javax.swing.JPopupMenu.Separator jSeparatorO;
    private javax.swing.JToolBar jTlBDataHora;
    // End of variables declaration//GEN-END:variables
}
