/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cadastro_2.java
 *
 * Created on 15/09/2012, 14:24:10
 */
package Interface;

/**
 *
 * @author aluno
 */
import Controle.ControleBasico;
import Controle.ControleFuncionarioDRH;
import Negocio.FuncionarioDRH;
import Util.Diversos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class JFrmFuncionarioDRH extends javax.swing.JFrame {

    ControleBasico cF;
    final String titulo;
  
    public JFrmFuncionarioDRH() {
        this.cF = new ControleFuncionarioDRH();
        this.titulo =  "Manipulação do(a) funcionario(a)";
        initComponents();
        setSize(450, 250);
        setResizable(false);
        setLocationRelativeTo(null);
        try {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
             IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrmFuncionarioDRH.class.getName()).log(Level.SEVERE, null, ex);
          }   
    }
     
    private void carregaObjetos(FuncionarioDRH f){
       jTxtInscricao.setText(String.valueOf(f.getInscricao()));
       jTxtNome.setText(f.getNome());  
    }   
    
    private void limpar() {
         JTextField txt[] = {jTxtInscricao, jTxtNome};
        for (JTextField t : txt)
            t.setText(""); 
       jTxtInscricao.setEditable(true); 
       jBtnIncluir.setEnabled(false);
       jBtnAlterar.setEnabled(false);
       jBtnExcluir.setEnabled(false);
       jTxtNome.requestFocusInWindow();
    }       
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblInscricao = new javax.swing.JLabel();
        jTxtInscricao = new javax.swing.JTextField();
        jLblNome = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblInscricao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblInscricao.setText("Inscrição");
        getContentPane().add(jLblInscricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        jTxtInscricao.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtInscricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtInscricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtInscricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtInscricaoFocusLost(evt);
            }
        });
        getContentPane().add(jTxtInscricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 100, 27));

        jLblNome.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jLblNome.setText("Nome");
        getContentPane().add(jLblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 28));

        jTxtNome.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jTxtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtNomeKeyReleased(evt);
            }
        });
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 270, 28));

        jPnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnIncluir.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnRetornar.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        jBtnRetornar.setText("Retornar");
        jBtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBtnIncluir)
                .addGap(26, 26, 26)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnLimpar)
                .addGap(18, 18, 18)
                .addComponent(jBtnRetornar)
                .addContainerGap())
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnLimpar)
                    .addComponent(jBtnRetornar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 420, -1));

        setSize(new java.awt.Dimension(445, 202));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jBtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRetornarActionPerformed
// TODO add your handling code here:
     if (Diversos.confirmar("Deseja retornar?", titulo))
        dispose();
}//GEN-LAST:event_jBtnRetornarActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
   jTxtNome.requestFocusInWindow(); 
}//GEN-LAST:event_formWindowActivated

private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
// TODO add your handling code here:
   limpar();
}//GEN-LAST:event_jBtnLimparActionPerformed

private void jTxtInscricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtInscricaoFocusLost
// TODO add your handling code here:
    int matricula; 
    Object o; 
    FuncionarioDRH f;
     if(!Diversos.testaNum(jTxtInscricao.getText(), titulo))
         jTxtInscricao.setText("");
     else if (!Diversos.intervalo(Integer.parseInt(jTxtInscricao.getText()), 0, 0, titulo))
               jTxtInscricao.setText("");
            else {
                    matricula = Integer.parseInt(jTxtInscricao.getText());
                    o = cF.getBusca(matricula,0);
                   if (o == null) {
                      jBtnIncluir.setEnabled(true);
                      Diversos.mostrarDados("Funcionario(a) Inexistente",titulo,false);
                  }    
                  else{ 
                        f = (FuncionarioDRH) o;                       
                        carregaObjetos(f);
                        jBtnAlterar.setEnabled(true);
                        jBtnExcluir.setEnabled(true);   
                 }                
           }
      jTxtInscricao.setEditable(false);                                          
}//GEN-LAST:event_jTxtInscricaoFocusLost

private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
// TODO add your handling code here:
   if (Diversos.confirmar("Deseja remover o(a) funcionário(a)", titulo)) {
       Object o = cF.getBusca(Integer.parseInt( jTxtInscricao.getText()), 0);
       FuncionarioDRH f = (FuncionarioDRH) o;  
       if (cF.setManipular(f, 'E')) {
            Diversos.mostrarDados("O(A) funcionarioDRH(a) " + jTxtNome.getText() + 
                  " foi removido com sucesso!!!", titulo, true);
           jBtnLimparActionPerformed(evt);
           jBtnAlterar.setEnabled(false);
           jBtnExcluir.setEnabled(false);            
       }
       else
         Diversos.mostrarDados("Problema ao remover o(a) funcionarioDRH(a) " + 
                 jTxtNome.getText() , titulo, false);
           
    }               
}//GEN-LAST:event_jBtnExcluirActionPerformed

private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
// TODO add your handling code here:
      if (jTxtInscricao.getText().isEmpty() || jTxtNome.getText().isEmpty() )
        Diversos.mostrarDados("Preencha todos os dados", titulo, false);
      else {
             FuncionarioDRH f = new FuncionarioDRH();
             f.setInscricao(Integer.parseInt(jTxtInscricao.getText()));
             f.setNome(jTxtNome.getText());
             if (jBtnIncluir.isEnabled()) {
                    if (cF.setManipular(f, 'I')) { //== true
                       Diversos.mostrarDados("O(A) funcionarioDRH(a) " +
                          jTxtNome.getText() + " foi inserido(a) com sucesso", titulo, true);
                       jBtnAlterar.setEnabled(true);
                       jBtnExcluir.setEnabled(true);
                   }
                   else //== false
                         Diversos.mostrarDados("Problemas ao inserir os dados " +
                              "do(a) funcionarioDRH(a) " + jTxtNome.getText(), titulo, false);                       
                 jBtnIncluir.setEnabled(false); 
                 
             }     
             else if (cF.setManipular(f,'A')) 
                        Diversos.mostrarDados("O(A) funcionarioDRH(a) " + jTxtNome.getText() +
                             " foi atualizado(a) com sucesso", titulo, true);              
                    else {
                           Diversos.mostrarDados("Problemas ao atualizar os dados "
                                 + "do(a) funcionarioDRH(a) " + jTxtNome.getText(), titulo, false);                                   
                           jBtnAlterar.setEnabled(false);
                          jBtnExcluir.setEnabled(false);
                   }           
       }
}//GEN-LAST:event_jBtnIncluirActionPerformed

private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
// TODO add your handling code here:
    jBtnIncluirActionPerformed(evt);
}//GEN-LAST:event_jBtnAlterarActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    limpar();
}//GEN-LAST:event_formWindowOpened

    private void jTxtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNomeKeyReleased
        // TODO add your handling code here:
        jTxtNome.setText(jTxtNome.getText().toUpperCase());
    }//GEN-LAST:event_jTxtNomeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmFuncionarioDRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmFuncionarioDRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmFuncionarioDRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmFuncionarioDRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFrmFuncionarioDRH().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnRetornar;
    private javax.swing.JLabel jLblInscricao;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JTextField jTxtInscricao;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
