/*Nome Nicolas Vycas Nery
*Turma 2111
*/
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class JFrmTemperatura extends javax.swing.JFrame {

    
    /**
     * Creates new form JFrmProduto
     */
    int incri[];//numero de incricao das cidades
    int poplc[];//população das cidades
    String nome[];//nomes das cidades
    float tmprtrs[][];//guarda as 4 temperaturas de cada cidade
    float tmpmedia[];
    String mponderada[];
    String situacao[];
    
    float mTmpG ,mt;// Media das temperaturas geral , 
    int ndcr;
    
    final int cidade = 4,tes = 4; //cidades contrala o numero maximo de cidades 
                                   //a ser registradas tes contrala quantas temperaturas cada cidade tem
    
    public JFrmTemperatura() {//construtor
         
        incri = new int[cidade];
        poplc = new int[cidade];
        nome = new String[cidade];
        tmprtrs = new float[cidade][tes];
        tmpmedia = new float[cidade];
        mponderada = new String[cidade];
        situacao = new String[cidade];
        
        ndcr = 0;//Variavel armazena numero de cidades cadastradas
        
        initComponents();
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblInscricao = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jTxtInscricao = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jLblMostrar = new javax.swing.JLabel();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnCalcular = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnListar = new javax.swing.JButton();
        jBtnFinalizar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jPnlTemp = new javax.swing.JPanel();
        jTxtS1 = new javax.swing.JTextField();
        jTxtS2 = new javax.swing.JTextField();
        jTxtS3 = new javax.swing.JTextField();
        jTxtS4 = new javax.swing.JTextField();
        jLblS1 = new javax.swing.JLabel();
        jLblS2 = new javax.swing.JLabel();
        jLblS3 = new javax.swing.JLabel();
        jLblS4 = new javax.swing.JLabel();
        jLblMediaM = new javax.swing.JLabel();
        jLblMediaT = new javax.swing.JLabel();
        jLblSitua = new javax.swing.JLabel();
        jLblSituacao = new javax.swing.JLabel();
        jLblAferi = new javax.swing.JLabel();
        jLblAfericao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtARelatorio = new javax.swing.JTextArea();
        jLblMedia = new javax.swing.JLabel();
        jLblMediaG = new javax.swing.JLabel();
        jLblPopu = new javax.swing.JLabel();
        jTxtPopu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastros de temperaturas");
        setResizable(false);

        jLblInscricao.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblInscricao.setText("Inscricao");

        jLblNome.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblNome.setText("Nome");

        jTxtInscricao.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtInscricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtNome.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLblMostrar.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblMostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPnlBotoes.setBackground(new java.awt.Color(33, 186, 247));
        jPnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnCalcular.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        jBtnCalcular.setText("Calcular");
        jBtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnListar.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        jBtnListar.setText("Listar");
        jBtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarActionPerformed(evt);
            }
        });

        jBtnFinalizar.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        jBtnFinalizar.setText("Finalizar");
        jBtnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinalizarActionPerformed(evt);
            }
        });

        jBtnIncluir.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBtnIncluir)
                .addGap(38, 38, 38)
                .addComponent(jBtnCalcular)
                .addGap(37, 37, 37)
                .addComponent(jBtnLimpar)
                .addGap(45, 45, 45)
                .addComponent(jBtnListar)
                .addGap(46, 46, 46)
                .addComponent(jBtnFinalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCalcular)
                    .addComponent(jBtnLimpar)
                    .addComponent(jBtnListar)
                    .addComponent(jBtnFinalizar)
                    .addComponent(jBtnIncluir))
                .addContainerGap())
        );

        jPnlTemp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Temperaturas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noto Sans", 3, 14))); // NOI18N

        jTxtS1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtS2.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtS2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtS3.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtS3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtS4.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtS4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLblS1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblS1.setText("1° Semana");

        jLblS2.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblS2.setText("2° Semana");

        jLblS3.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblS3.setText("3° Semana");

        jLblS4.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblS4.setText("4° Semana");

        jLblMediaM.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblMediaM.setText("Média");

        jLblMediaT.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblMediaT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLblSitua.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblSitua.setText("Situação");

        jLblSituacao.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblSituacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLblAferi.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblAferi.setText("Aferição");

        jLblAfericao.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblAfericao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPnlTempLayout = new javax.swing.GroupLayout(jPnlTemp);
        jPnlTemp.setLayout(jPnlTempLayout);
        jPnlTempLayout.setHorizontalGroup(
            jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTempLayout.createSequentialGroup()
                .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlTempLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPnlTempLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jTxtS1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtS2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPnlTempLayout.createSequentialGroup()
                                .addComponent(jLblS1)
                                .addGap(56, 56, 56)
                                .addComponent(jLblS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99)
                        .addComponent(jTxtS3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtS4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblS4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlTempLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblMediaT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPnlTempLayout.createSequentialGroup()
                                .addComponent(jLblMediaM, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)))
                        .addGap(18, 18, 18)
                        .addComponent(jLblSitua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlTempLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLblAferi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblAfericao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlTempLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLblS3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlTempLayout.setVerticalGroup(
            jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTempLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblS1)
                    .addComponent(jLblS2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblS3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblS4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblMediaM)
                        .addGroup(jPnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblSituacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPnlTempLayout.createSequentialGroup()
                                .addComponent(jLblSitua)
                                .addGap(4, 4, 4))
                            .addComponent(jLblAferi)
                            .addComponent(jLblAfericao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlTempLayout.createSequentialGroup()
                        .addComponent(jLblMediaT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );

        jTxtARelatorio.setColumns(20);
        jTxtARelatorio.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtARelatorio.setRows(5);
        jTxtARelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(jTxtARelatorio);

        jLblMedia.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblMedia.setText("Média Geral");

        jLblMediaG.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblMediaG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLblPopu.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLblPopu.setText("População");

        jTxtPopu.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jTxtPopu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 123, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLblPopu)
                                .addGap(2, 2, 2)
                                .addComponent(jTxtPopu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMediaG, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblMostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblInscricao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jLblNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPnlTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblInscricao)
                    .addComponent(jTxtInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNome)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jPnlTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblPopu)
                        .addComponent(jTxtPopu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblMedia))
                    .addComponent(jLblMediaG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(931, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed

        if(//verifica se os campos estão preenchidos
        jTxtInscricao.getText().isEmpty()||
        jTxtNome.getText().isEmpty()||
        jTxtPopu.getText().isEmpty()||
        jTxtS1.getText().isEmpty()||
        jTxtS2.getText().isEmpty()||
        jTxtS3.getText().isEmpty()||
        jTxtS4.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Favor digitra todos os datos","Cadastros de temperaturas",JOptionPane.ERROR_MESSAGE);
        }else if(cidade == ndcr){//limite atingido
            JOptionPane.showMessageDialog(null, "Numero maximo de cidades registradas","Cadastros de temperaturas",JOptionPane.ERROR_MESSAGE);
        }else
            
        incri[ndcr] = Integer.parseInt(jTxtInscricao.getText());
        poplc [ndcr] = Integer.parseInt(jTxtPopu.getText());
        nome [ndcr] = jTxtNome.getText();
        
        tmprtrs [ndcr][0] = Float.parseFloat(jTxtS1.getText().replace(",", "."));
        tmprtrs [ndcr][1] = Float.parseFloat(jTxtS1.getText().replace(",", "."));
        tmprtrs [ndcr][2] = Float.parseFloat(jTxtS1.getText().replace(",", "."));
        tmprtrs [ndcr][3] = Float.parseFloat(jTxtS1.getText().replace(",", "."));
        
        //info();
        
        
        jBtnIncluir.setEnabled(false);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinalizarActionPerformed
       
        if(JOptionPane.showConfirmDialog(null, "deseja Finalizar?","Cadastros de temperaturas",JOptionPane.YES_NO_OPTION)==0)
           System.exit(0);
        
    }//GEN-LAST:event_jBtnFinalizarActionPerformed

    private void jBtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarActionPerformed
     String relatorio = "";
     
        jTxtARelatorio.setText("");
     
        for (int i = 0; i < cidade; i++) {
           
            relatorio += mostar(i)+"\n";
            
        }
 
        jTxtARelatorio.setText(relatorio);
        
    }//GEN-LAST:event_jBtnListarActionPerformed

    private void jBtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularActionPerformed
       
        /** MT = ((Temp1 X 4 + Temp2 X 3 + Temp3 X 2 + Temp4 ) / 10 mt define a afericao
        *  Muito calor > 40
        *  Calor 30,1 e <= 40
        *  Aceitavel 19,1 e 30,1
        *  Frio 4,1 e <= 19,1
        *  Muito frio < 4,1 
        **/
        
       // mt = (tmprtrs [ndcr][0]*4+tmprtrs [ndcr][1]*3+tmprtrs [ndcr][2]*2+tmprtrs [ndcr][3]*1)/10;
        
        //tmpmedia[ndcr] = mt;
        
        if( !jBtnIncluir.isEnabled()){
            
            
                mt = (tmprtrs [ndcr][0]*4+tmprtrs [ndcr][1]*3+tmprtrs [ndcr][2]*2+tmprtrs [ndcr][3]*1)/10;
                tmpmedia[ndcr] = mt;
                
                jLblMediaT.setText(Float.toString(tmpmedia[ndcr]));//poe a media no campo mediat
                
                //situicao
                
                if(tmpmedia[ndcr]>40){//Muito Calor
                    mponderada[ndcr] = "MC";
                }if(tmpmedia[ndcr]<=40 && tmpmedia[ndcr] > 30.1){//Calor
                    mponderada[ndcr] = "C";
                }if(tmpmedia[ndcr] <= 30.1 && tmpmedia[ndcr] > 19.1){//Aceitavel
                    mponderada[ndcr] = "A";
                }if(tmpmedia[ndcr] <=19.1 && tmpmedia[ndcr] > 4.1){//frio
                    mponderada[ndcr] = "F";
                }if(tmpmedia[ndcr] < 4.1){//muito frio
                    mponderada[ndcr] = "MF";
                }
                jLblAfericao.setText(mponderada[ndcr]); 
                
                mTmpG =+ tmpmedia[ndcr]/ndcr;
                
                if(tmpmedia[ndcr]>30.1){//acima da media
                    situacao[ndcr] = "Quente";
                }else if(tmpmedia[ndcr]<=19.1){//abaixo da media
                    situacao[ndcr] = "Frio";
                }else{//iqual a media
                    situacao[ndcr] = "Agradavel";
                }
                jLblSituacao.setText(situacao[ndcr]);
                
                jLblMediaG.setText(Float.toString(mTmpG));
               
                jLblMostrar.setText(mostar(ndcr));
                
                ndcr++;
                
            }else 
            JOptionPane.showMessageDialog(null, "Dados não digitados","Cadastros de temperaturas",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jBtnCalcularActionPerformed
    
    String mostar(int pos){//pos posição no array
        // metodo serve para mostras o resultado
        String saida;
        
        saida = "Inscricao:"+incri[pos]+"Nome:"+nome[pos]+" Popu:"+poplc[pos]+" Media T:"+tmpmedia[pos]+" Media P: "+mponderada[pos]+" Situacao:"+situacao[pos]+
                "T1: "+tmprtrs[pos][0]+"T2: "+tmprtrs[pos][1]+"T3: "+tmprtrs[pos][2]+"T4: "+tmprtrs[pos][3];
        
        return saida;
    }
    
    
    void limpar(){ //Metodo para limpar os campos
               
        //jTxtARelatorio.setText("");
        jTxtInscricao.setText("");
        jTxtNome.setText("");
        jTxtPopu.setText("");
        jTxtS1.setText("");
        jTxtS2.setText("");
        jTxtS3.setText("");
        jTxtS4.setText("");
        
        jLblMediaT.setText("");
        jLblSituacao.setText("");
        jLblAfericao.setText("");
        jLblMediaG.setText("");
        jLblMostrar.setText("");
        
        jBtnIncluir.setEnabled(true);
    }// fim do limpar
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrmTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalcular;
    private javax.swing.JButton jBtnFinalizar;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnListar;
    private javax.swing.JLabel jLblAferi;
    private javax.swing.JLabel jLblAfericao;
    private javax.swing.JLabel jLblInscricao;
    private javax.swing.JLabel jLblMedia;
    private javax.swing.JLabel jLblMediaG;
    private javax.swing.JLabel jLblMediaM;
    private javax.swing.JLabel jLblMediaT;
    private javax.swing.JLabel jLblMostrar;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblPopu;
    private javax.swing.JLabel jLblS1;
    private javax.swing.JLabel jLblS2;
    private javax.swing.JLabel jLblS3;
    private javax.swing.JLabel jLblS4;
    private javax.swing.JLabel jLblSitua;
    private javax.swing.JLabel jLblSituacao;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JPanel jPnlTemp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtARelatorio;
    private javax.swing.JTextField jTxtInscricao;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtPopu;
    private javax.swing.JTextField jTxtS1;
    private javax.swing.JTextField jTxtS2;
    private javax.swing.JTextField jTxtS3;
    private javax.swing.JTextField jTxtS4;
    // End of variables declaration//GEN-END:variables
}
